spring.application.name=webapp

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.egpbxyqfctlmxvmvuxmq
spring.datasource.password=amitamitnilaic

# SSL 
spring.datasource.hikari.data-source-properties.sslmode=require

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# FIX CHUNKED ERROR
server.compression.enabled=false
server.tomcat.connection-timeout=60000
server.tomcat.max-swallow-size=-1

# DEVTOOLS FIX
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false

# Tambahan Konfigurasi untuk Batas Ukuran Upload Gambar (Maksimal 10MB)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
server.tomcat.max-swallow-size=-1

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=afaninmusfida1@gmail.com
spring.mail.password=aysd thlc ndzo dxgp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Cloudinary
cloudinary.cloud-name=dygxpayai
cloudinary.api-key=424185822423831
cloudinary.api-secret=kqV655Y0A26Eswd7EHtOtk4XOyE
